[workspace]
members = [
    "crates/*",
    "delta-inspect",
    "python",
]
exclude = ["proofs"]
resolver = "2"

[workspace.package]
authors = ["Qingping Hou <dave2008713@gmail.com>"]
rust-version = "1.72"
keywords = ["deltalake", "delta", "datalake"]
readme = "README.md"
edition = "2021"
description = "Native Delta Lake implementation in Rust"
homepage = "https://github.com/delta-io/delta.rs"
license = "Apache-2.0"
documentation = "https://docs.rs/deltalake"
repository = "https://github.com/delta-io/delta.rs"

[profile.release-with-debug]
inherits = "release"
debug = true

# Reducing the debuginfo for the test profile in order to trim the disk and RAM
# usage during development
# <https://github.com/delta-io/delta-rs/issues/1550?
[profile.test]
debug = "line-tables-only"

[workspace.dependencies]
# arrow
arrow = { git = "https://github.com/Nekit2217/arrow-rs", branch="decimal-e-notation" }
arrow-arith = { git = "https://github.com/Nekit2217/arrow-rs", branch="decimal-e-notation" }
arrow-array = { git = "https://github.com/Nekit2217/arrow-rs", branch="decimal-e-notation", features = ["chrono-tz"]}
arrow-buffer = { git = "https://github.com/Nekit2217/arrow-rs", branch="decimal-e-notation" }
arrow-cast = { git = "https://github.com/Nekit2217/arrow-rs", branch="decimal-e-notation" }
arrow-ipc = { git = "https://github.com/Nekit2217/arrow-rs", branch="decimal-e-notation" }
arrow-json = { git = "https://github.com/Nekit2217/arrow-rs", branch="decimal-e-notation" }
arrow-ord = { git = "https://github.com/Nekit2217/arrow-rs", branch="decimal-e-notation" }
arrow-row = { git = "https://github.com/Nekit2217/arrow-rs", branch="decimal-e-notation" }
arrow-schema = { git = "https://github.com/Nekit2217/arrow-rs", branch="decimal-e-notation" }
arrow-select = { git = "https://github.com/Nekit2217/arrow-rs", branch="decimal-e-notation" }
object_store = { version = "0.9" }
parquet = { git = "https://github.com/Nekit2217/arrow-rs", branch="decimal-e-notation" }

# datafusion
#datafusion = { version = "36" }
#datafusion-expr = { version = "36" }
#datafusion-common = { version = "36" }
#datafusion-proto = { version = "36" }
#datafusion-sql = { version = "36" }
#datafusion-physical-expr = { version = "36" }
#datafusion-functions = { version = "36" }
datafusion = { git = "https://github.com/Nekit2217/arrow-datafusion", branch="main" }
datafusion-expr = { git = "https://github.com/Nekit2217/arrow-datafusion", branch="main" }
datafusion-common = { git = "https://github.com/Nekit2217/arrow-datafusion", branch="main" }
datafusion-proto = { git = "https://github.com/Nekit2217/arrow-datafusion", branch="main" }
datafusion-sql = { git = "https://github.com/Nekit2217/arrow-datafusion", branch="main" }
datafusion-physical-expr = { git = "https://github.com/Nekit2217/arrow-datafusion", branch="main" }
datafusion-functions = { git = "https://github.com/Nekit2217/arrow-datafusion", branch="main" }


# serde
serde = { version = "1.0.194", features = ["derive"] }
serde_json = "1"

# "stdlib"
bytes = { version = "1" }
chrono = { version = ">0.4.34", default-features = false, features = ["clock"] }
tracing = { version = "0.1", features = ["log"] }
regex = { version = "1" }
thiserror = { version = "1" }
url = { version = "2" }
uuid = { version = "1" }

# runtime / async
async-trait = { version = "0.1" }
futures = { version = "0.3" }
tokio = { version = "1" }
num_cpus = { version = "1" }
